I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script00.rpy", line 500, in script call
    call dungeon
  File "game/script00.rpy", line 580, in script
    $ current_battle = Battle()
  File "game/script00.rpy", line 580, in <module>
    $ current_battle = Battle()
  File "game/dungeonBattle.rpy", line 36, in __init__
    self.loadBattle(battleNumber)
  File "game/dungeonBattle.rpy", line 65, in loadBattle
    self.initialize()
  File "game/dungeonBattle.rpy", line 86, in initialize
    self.targetArrow.rect.bottom = self.enemies[self.target].rect.centery
AttributeError: 'Battle' object has no attribute 'targetArrow'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script00.rpy", line 500, in script call
    call dungeon
  File "game/script00.rpy", line 580, in script
    $ current_battle = Battle()
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/ast.py", line 785, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/digiholic/workspace/SummonerSweetheart-0.9-all/renpy/python.py", line 1382, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script00.rpy", line 580, in <module>
    $ current_battle = Battle()
  File "game/dungeonBattle.rpy", line 36, in __init__
    self.loadBattle(battleNumber)
  File "game/dungeonBattle.rpy", line 65, in loadBattle
    self.initialize()
  File "game/dungeonBattle.rpy", line 86, in initialize
    self.targetArrow.rect.bottom = self.enemies[self.target].rect.centery
AttributeError: 'Battle' object has no attribute 'targetArrow'

Linux-3.11.0-26-generic-x86_64-with-debian-wheezy-sid
Ren'Py 6.18.3.761
Summoner Sweetheart 0.9
